// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddProject(name: string, path: string): $CancellablePromise<$models.Project> {
    return $Call.ByID(3415003096, name, path);
}

export function Cancel(session: string): $CancellablePromise<void> {
    return $Call.ByID(404152658, session);
}

export function Connect(baseURL: string, username: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(1210147758, baseURL, username, password);
}

export function DeleteProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(654211872, id);
}

export function DeleteSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(4044255501, id);
}

export function Directories(path: string): $CancellablePromise<$models.DirectoryResponse> {
    return $Call.ByID(2360697339, path);
}

export function NewSession(projectID: string): $CancellablePromise<$models.SessionDetail> {
    return $Call.ByID(2600216170, projectID);
}

export function OpenSession(id: string): $CancellablePromise<$models.SessionDetail> {
    return $Call.ByID(1574619468, id);
}

export function Projects(): $CancellablePromise<$models.Project[] | null> {
    return $Call.ByID(811711002);
}

export function ResumeRuns(): $CancellablePromise<$models.RunSummary[] | null> {
    return $Call.ByID(3583972733);
}

export function Send(session: string, prompt: string): $CancellablePromise<void> {
    return $Call.ByID(3221561526, session, prompt);
}

export function Sessions(projectID: string): $CancellablePromise<$models.Session[] | null> {
    return $Call.ByID(3365999221, projectID);
}
