// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddProject(name: string, path: string): $CancellablePromise<$models.Project> {
    return $Call.ByID(3415003096, name, path);
}

export function ArtifactSource(session: string, id: string): $CancellablePromise<string> {
    return $Call.ByID(3915958247, session, id);
}

export function Bots(): $CancellablePromise<$models.Bot[] | null> {
    return $Call.ByID(2070968066);
}

export function Cancel(session: string): $CancellablePromise<void> {
    return $Call.ByID(404152658, session);
}

export function Commands(): $CancellablePromise<$models.BotCommand[] | null> {
    return $Call.ByID(1511692198);
}

export function Connect(baseURL: string, username: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(1210147758, baseURL, username, password);
}

export function Connectors(): $CancellablePromise<$models.Connector[] | null> {
    return $Call.ByID(4168191744);
}

export function DeleteBot(id: string): $CancellablePromise<void> {
    return $Call.ByID(3488197120, id);
}

export function DeleteConnector(id: string): $CancellablePromise<void> {
    return $Call.ByID(33325902, id);
}

export function DeleteProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(654211872, id);
}

export function DeleteSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(4044255501, id);
}

export function Directories(path: string): $CancellablePromise<$models.DirectoryResponse> {
    return $Call.ByID(2360697339, path);
}

export function NewSession(projectID: string, botID: string): $CancellablePromise<$models.SessionDetail> {
    return $Call.ByID(2600216170, projectID, botID);
}

export function OpenSession(id: string): $CancellablePromise<$models.SessionDetail> {
    return $Call.ByID(1574619468, id);
}

export function ProjectFiles(project: string, query: string): $CancellablePromise<$models.BotFileHit[] | null> {
    return $Call.ByID(356402088, project, query);
}

export function Projects(): $CancellablePromise<$models.Project[] | null> {
    return $Call.ByID(811711002);
}

export function ResumeRuns(): $CancellablePromise<$models.RunSummary[] | null> {
    return $Call.ByID(3583972733);
}

export function SaveBot(item: $models.Bot): $CancellablePromise<$models.Bot> {
    return $Call.ByID(3169410574, item);
}

export function SaveConnector(item: $models.Connector): $CancellablePromise<$models.Connector> {
    return $Call.ByID(3536322592, item);
}

export function Send(session: string, prompt: string): $CancellablePromise<void> {
    return $Call.ByID(3221561526, session, prompt);
}

export function Sessions(projectID: string): $CancellablePromise<$models.Session[] | null> {
    return $Call.ByID(3365999221, projectID);
}

export function Steer(session: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(2007742073, session, text);
}
