// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Artifact {
    "id": string;
    "name": string;
    "media_type": string;
    "size": number;
}

export interface Bot {
    "id"?: string;
    "name": string;
    "prompt": string;
    "tools": string[] | null;
    "workspace_root": string;
    "skill_root"?: string;
    "model"?: string;
}

export interface BotCommand {
    "name": string;
    "description": string;
}

export interface BotFileHit {
    "path": string;
}

export interface Connector {
    "id"?: string;
    "name": string;
    "type": string;
    "bot_id": string;
    "project_id": string;
    "enabled": boolean;
    "status"?: string;
    "error"?: string;
    "restarts"?: number;
}

export interface Directory {
    "name": string;
    "path": string;
    "kind"?: string;
    "registered": boolean;
}

export interface DirectoryResponse {
    "path"?: string;
    "parent"?: string;
    "roots"?: DirectoryRoot[] | null;
    "directories"?: Directory[] | null;
}

export interface DirectoryRoot {
    "name": string;
    "path": string;
}

export interface Message {
    "role": string;
    "content": string;
    "tool_calls"?: ToolCall[] | null;
    "tool_call_id"?: string;
}

export interface Project {
    "id"?: string;
    "name": string;
    "path"?: string;
}

export interface RunSummary {
    "id": string;
    "session_id": string;
    "status": string;
}

export interface Session {
    "id": string;
    "project_id": string;
    "bot_id"?: string;
    "title": string;
    "updated_at": string;
}

export interface SessionDetail {
    "id": string;
    "project_id": string;
    "bot_id"?: string;
    "title": string;
    "updated_at": string;
    "messages": Message[] | null;
    "artifacts": Artifact[] | null;
}

export interface StreamEvent {
    "type": string;
    "session_id"?: string;
    "run_id"?: string;
    "sequence"?: number;
    "id"?: string;
    "name"?: string;
    "arguments"?: string;
    "text"?: string;
    "output"?: string;
}

export interface ToolCall {
    "id": string;
    "name": string;
    "arguments": string;
}
